### ISSUE TITLE
[MONO-LINUX] Not reading all ratings in IMDb CSV file?

### ISSUE THREAD

**Issue by Kevin-Mok** [damienhaynes/TraktRater#100]
My IMDb CSV file contains 360 ratings, yet the log shows that it only found 18 movie ratings and 19 TV show ratings. I tried increasing the batch import to 400, but it didn't change anything. How do I get it to read all the ratings? Here are [the files](https://github.com/damienhaynes/TraktRater/files/3488480/imdb-import.zip) as a zip for reference.

**Comment by damienhaynes** [comment]
Hi Kevin-Mok,

I tried your import file and it found 224 movies. Are you sure you are pointing to the correct file?

FYI you don't need to set the batch import to 400, 50 will suffice.

**Comment by damienhaynes** [comment]
I did notice there is something wrong with the episode rating import but that is something different to what you reported and is due to a change with the TVDb API, I will see what I can do with fixing that.

**Comment by Kevin-Mok** [comment]
I just double-checked the file, and it is the same one I posted. I just reran it again with the same result. That's so strange. I'm using the latest released binary (2.3.5), but I'm running it with Mono on Linux. Could that possibly affect anything? Do I need to recompile it from source?

**Comment by damienhaynes** [comment]
That's very strange indeed, I can't see why it would be any different under Mono. Here is snipet of the log I see:

**Comment by damienhaynes** [comment]
Can you try the following executable as I added some logging when it processes each line of the CSV...it may help track down why its not picking up the movies as expected.

[TraktRater.zip](https://github.com/damienhaynes/TraktRater/files/3488526/TraktRater.zip)

**Comment by Kevin-Mok** [comment]
So, I just tried it on Windows, and it works basically as expected except the episode problem like you mentioned. I tried out the logging executable, and [here's the log](https://github.com/damienhaynes/TraktRater/files/3488538/20190810_011154.log) for that.

When I run `xbuild` (Mono's version of `msbuild`) on `TraktRater.csproj`, I get errors about `CsvHelper` being found. Would it need that package to run the executable itself or just for building?

**Comment by damienhaynes** [comment]
I see what the problem is. For some reason when running it with Mono it gets spooked by the fields containing Quotes e.g. 

tt1010048,9,2016-06-27,Slumdog Millionaire,https://www.imdb.com/title/tt1010048/,movie,8.0,120,2008,**"Drama, Romance"**,751449,2008-08-30,**"Loveleen Tandan, Danny Boyle"**

I'm using a TextFieldParser in the Microsoft.VisualBasic.FileIO namespace to handle parsing, I will see if there is a way to fix that. I probably should just upgrade the IMDb import to use CSVHelper which is a great library for CSVs, I'm using in other places.

Regarding your error, there is a post build step (in Release mode) which merges the exe with CSVHelper.dll, it might have something to do with that?

**Comment by damienhaynes** [comment]
I found a property aptly named 'HasFieldsEnclosedInQuotes' which I just set to true. Can you please try again with attached exe.

[TraktRater.zip](https://github.com/damienhaynes/TraktRater/files/3488661/TraktRater.zip)

**Comment by Kevin-Mok** [comment]
No difference. :worried: I mean at least I got it to import on Windows, and it's not something I really need to do more than once. But, I guess if you wanted to fix this cross-compatibility issue.

**Comment by damienhaynes** [comment]
Alright, thanks for testing anyway.

**Comment by Kevin-Mok** [comment]
Yeah, thanks for checking out my CSV file for me. :smile:

**Comment by arkanath** [comment]
I also have the same issue, can confirm the latest fix with HasFieldsEnclosedInQuotes still isn't working. I am using Wine instead of Mono, mono didn't work for me. I manually removed the Genres and Directors fields in csv to remove the quote fields and was able to import most but an update to fix this will be absolutely useful.

**Comment by damienhaynes** [comment]
@arkanath and @Kevin-Mok if you are keen, I have attached a new Traktrater which should hopefully work better. 

I have tested myself on an Ubunto VM and appears to work nicely.
[TraktRater.zip](https://github.com/damienhaynes/TraktRater/files/3512686/TraktRater.zip)

**Comment by Kevin-Mok** [comment]
Yep, used the same IMDb file as before, and now it finds the 224 movies. Nice!

**Comment by damienhaynes** [comment]
Thanks!
