### ISSUE TITLE
IMDB scraper returns 403

### ISSUE THREAD

**Issue by yitzhaq** [damienhaynes/TraktRater#103]
When attempting to sync IMDB watchlist using scraper, it fails. Logs show IMDB returning 403, whereas a request from the same IP in a browser, without authentication (private window), successfully returns the watchlist (which has been made public prior to testing).

I haven't tried sniffing which UA the scraper uses, but if that's what's being discriminated against, it might be worth trying to spoof as a current browser to see if that works any better.

Also, if you're able to support HTTPS, you should probably switch the IMDB URL to use it instead of HTTP. In fact, it might be worth going through all third party URLs that get called - I can't imagine any of the supported services not supporting HTTPS today.

**Comment by krishnamuppaneni** [comment]
Hi, I am working on an efficient way to import IMDb watchlist. Instead of scrapping the titles from web page, we can scrape Watchlist ID and download the .CVS file from following Url. 

http://www.imdb.com/list/[listID]/export 

I have a working version ready for Watchlist but Ratings list cannot be implemented in the same manner. I'll submit a pull request once I am done working on Ratings list.

**Comment by damienhaynes** [comment]
Thanks @krishnamuppaneni, I haven't invested too much effort in the IMDb scraping provider so anything you can address to improve/fix in that area will be much appreciated.
