### ISSUE TITLE
Can get the backuped Trakt data be restored?

### ISSUE THREAD

**Issue by jack1142** [damienhaynes/TraktRater#130]

**Comment by damienhaynes** [comment]
Do you mean the exported data? If yes, then not as yet but in a future task to be implemented, yes it will.

**Comment by jack1142** [comment]
Yeah, I meant to ask whether the exported data can be imported back to Trakt. Is there any other tracking issue for this? I couldn't find one.

**Comment by damienhaynes** [comment]
There are a few open issues such as #119, #63, #13, I think there are a few more but they are more or less the same ;)

**Comment by jack1142** [comment]
Guess I didn't try searching hard enough, thanks :)

**Comment by WybeBosch** [comment]
Unsure if this project is still being watched, but i would be very interested in this aswell!
(The whole create ofline backups of trakt, and being able to Restore them)

Since often if you use other apps / tooling that syncs with trakt, 1 wrong button click and you could wipe your entire trakt history T_T
(Such as i did when used Jellyfin and i synced watched status from a fresh library to trakt and promptly it unwatched all my series and movies in trakt.)

**Comment by damienhaynes** [comment]
@WybeBosch, I will definitely get to this and related tasks, I just need an opening in my life schedule...tough year.
