### ISSUE TITLE
Rated movie count does not equal Watched movie count

### ISSUE THREAD

**Issue by Residentcl** [damienhaynes/TraktRater#30]
but I can not yet complete list Trakt view movies from IMDB.
No idea if it will be a mistake by the app or Trakt with the new site.

http://www.imdb.com/user/ur22929128/watchlist
http://trakt.tv/users/residentcl/history/movies/added

log CSV inport:
http://pastebin.com/cjvS96Sz
log web scrape:
http://pastebin.com/g8VPfWT2

CSV WATCHLIST: https://mega.co.nz/#!v94wDYiS!tZcSmEsE88jQO4y7tziTfzUx7Kc7Izp63D2uhCMGrss
System Windows 8.1 update 1.
Problem TraktRater 2.0.0 and 2.0.1

**Comment by damienhaynes** [comment]
If you see the logs you will notice you're getting a lot of 502 errors e.g.
Response: Error en el servidor remoto: (502) Puerta de enlace no válida.

This is an issue with Trakt right now, can you try again later until all 502 errors go away.

**Comment by damienhaynes** [comment]
fyi, according to your CSV you have 288 movie ratings:
"Found 288 movie ratings in CSV file"

And according to the trakt website, you have 288 movies rated:
"Found 288 user movie ratings on trakt.tv"

The TraktRater app will not mark any of you rated movies as watched, because it will only mark as watched anything new you haven't rated on trakt.tv.
"Importing 0 new IMDb movie ratings to trakt.tv"

Because there is 0 movies to send to trakt.tv, it wont mark anything new as watched.

You can test this theory by adding a new rating on CSV, it will mark that movie as watched if you enable that option in TraktRater.

I could probably check all your rated movies to see if they're watched instead of only the ones you have not rated yet on trakt.tv.

**Comment by damienhaynes** [comment]
I have renamed the title of this issue to better reflect what you want (at least that's what I think you want).

So in this case, if you have 288 movies rated on IMDb then you want 288 movies watched on trakt.tv. This is a good enhancement as opposed to only setting watched on what is not rated so far esp. if sync stopped due to server issue after ratings import had complete.

**Comment by damienhaynes** [comment]
I should also point out, I do not mark Shows as watched, because I do not know if you have watched the entire show from rating it. Sometimes people rate a show after watching a few episodes.

**Comment by Residentcl** [comment]
Now it goes well, yesterday was much less, probably was a mistake by Trakt.
Apart need to remove from the list the series, and the list is complete.

Damienhaynes thank you very much for all your help :)
We closed the topic.
Thank you very much, Greetings from Chile.
