### ISSUE TITLE
Unable to add various titles to Criticker - any way to easily find out which?

### ISSUE THREAD

**Issue by sneedsfeedandseed** [damienhaynes/TraktRater#85]
I exported like 2500 films from criticker to trakt and it missed hundreds. Now, that in itself is a problem but I wouldn't mind adding them by hand TOO much... but I have no easy way of finding out which ones were left out. Is there any way I can do that? The logs don't seem to show which ones couldn't be added. Could this functionality be added, or criticker transferral be improved? 

Thanks

**Comment by damienhaynes** [comment]
Yeah, I should be able to extract from the response which ones did not get added.

If I recall correctly the biggest problem from importing from Criticker is that it does not provide movies by common ID's e.g. IMDb ID or TMDb ID which trakt.tv uses to identify movies. It can only rely on the correct movie title and year which is not the best and hence why so many failed.

**Comment by damienhaynes** [comment]
If you post your log, I can help you identify without a new release.

**Comment by sneedsfeedandseed** [comment]
Cool, that'd be much appreciated. I actually have two, one for me and one for my friend. Hopefully that's not too much trouble.

[20180214_101029.log](https://github.com/damienhaynes/TraktRater/files/1725977/20180214_101029.log)
[20180214_091835.log](https://github.com/damienhaynes/TraktRater/files/1725978/20180214_091835.log)

**Comment by damienhaynes** [comment]
Here is a tip (because you have a lot), look for lines with "Response: " and grab everything including the curly braces e.g.

{"added":{"movies":10,"shows":0,"seasons":0,"episodes":0},"not_found":{"movies":[{"ids":null,"title":"Breaking Bad","year":2008,"rated_at":"2015-10-17T04:33:00Z","rating":9},{"ids":null,"title":"South Park","year":1997,"rated_at":"2015-10-17T04:06:00Z","rating":9},{"ids":null,"title":"Naruto: Shippûden","year":2007,"rated_at":"2016-08-06T04:58:00Z","rating":9},{"ids":null,"title":"Rocko's Modern Life","year":1993,"rated_at":"2015-10-17T02:02:00Z","rating":9},{"ids":null,"title":"South Park: Bigger, Longer, and Uncut","year":1999,"rated_at":"2013-03-21T00:10:00Z","rating":9},{"ids":null,"title":"Animaniacs","year":1993,"rated_at":"2015-10-17T02:22:00Z","rating":9},{"ids":null,"title":"Invader ZIM","year":2001,"rated_at":"2015-10-17T02:07:00Z","rating":9},{"ids":null,"title":"Band of Brothers","year":2001,"rated_at":"2013-03-21T02:10:00Z","rating":9},{"ids":null,"title":"Curb Your Enthusiasm","year":1999,"rated_at":"2015-10-17T04:22:00Z","rating":9},{"ids":null,"title":"Hey Arnold!","year":1996,"rated_at":"2015-10-17T02:03:00Z","rating":9},{"ids":null,"title":"It's Always Sunny in Philadelphia","year":2005,"rated_at":"2015-10-17T04:13:00Z","rating":9},{"ids":null,"title":"The Pacific","year":2010,"rated_at":"2013-03-21T02:09:00Z","rating":9},{"ids":null,"title":"Pinky and the Brain","year":1995,"rated_at":"2015-10-17T02:27:00Z","rating":9},{"ids":null,"title":"Samurai X: Trust and Betrayal","year":1999,"rated_at":"2013-03-21T17:36:00Z","rating":8},{"ids":null,"title":"Superman: The Animated Series","year":1996,"rated_at":"2015-10-17T02:48:00Z","rating":8},{"ids":null,"title":"Avatar: The Last Airbender","year":2005,"rated_at":"2015-10-17T02:09:00Z","rating":8},{"ids":null,"title":"Tiny Toon Adventures","year":1990,"rated_at":"2015-10-17T02:27:00Z","rating":8},{"ids":null,"title":"Cowboy Bebop","year":1998,"rated_at":"2016-08-06T20:52:00Z","rating":8},{"ids":null,"title":"Kill Bill: Volume 1","year":2003,"rated_at":"2013-03-20T22:42:00Z","rating":8},{"ids":null,"title":"Scrubs","year":2001,"rated_at":"2015-10-17T03:57:00Z","rating":8},{"ids":null,"title":"American Dad","year":2005,"rated_at":"2015-10-17T04:03:00Z","rating":8},{"ids":null,"title":"Beast Wars: Transformers","year":1996,"rated_at":"2016-08-07T23:40:00Z","rating":8},{"ids":null,"title":"Dragon Ball Z","year":1989,"rated_at":"2016-08-06T05:00:00Z","rating":8},{"ids":null,"title":"Drawn Together","year":2004,"rated_at":"2015-10-17T04:10:00Z","rating":8},{"ids":null,"title":"Harvey Birdman, Attorney at Law","year":2000,"rated_at":"2015-10-17T02:50:00Z","rating":8},{"ids":null,"title":"Johnny Bravo","year":1997,"rated_at":"2015-10-17T02:40:00Z","rating":8},{"ids":null,"title":"The New Batman Adventures","year":1997,"rated_at":"2015-10-17T02:48:00Z","rating":8},{"ids":null,"title":"Rugrats","year":1990,"rated_at":"2015-10-17T02:02:00Z","rating":8},{"ids":null,"title":"Aaahh!!! Real Monsters","year":1994,"rated_at":"2015-10-17T02:03:00Z","rating":8},{"ids":null,"title":"Kill Bill: Volume 2","year":2004,"rated_at":"2013-03-20T22:44:00Z","rating":8},{"ids":null,"title":"Samurai X","year":1996,"rated_at":"2016-08-06T05:05:00Z","rating":8},{"ids":null,"title":"Aqua Teen Hunger Force","year":2000,"rated_at":"2015-10-17T02:21:00Z","rating":8},{"ids":null,"title":"Mobile Suit Gundam: The 08th MS Team","year":1996,"rated_at":"2016-08-06T05:13:00Z","rating":8},{"ids":null,"title":"The Ren & Stimpy Show","year":1991,"rated_at":"2015-10-17T02:02:00Z","rating":8},{"ids":null,"title":"Russia, Land of the Tsars","year":2003,"rated_at":"2015-10-17T04:46:00Z","rating":8},{"ids":null,"title":"X2: X-Men United","year":2003,"rated_at":"2013-03-20T22:20:00Z","rating":8},{"ids":null,"title":"Fullmetal Alchemist: Brotherhood","year":2009,"rated_at":"2016-08-06T05:21:00Z","rating":8},{"ids":null,"title":"Batman: The Animated Series","year":1992,"rated_at":"2015-10-17T02:48:00Z","rating":8},{"ids":null,"title":"Jackass","year":2000,"rated_at":"2015-10-17T22:15:00Z","rating":8},{"ids":null,"title":"Mobile Suit Gundam Wing","year":1995,"rated_at":"2016-08-06T05:12:00Z","rating":8}],"shows":[],"seasons":[],"episodes":[],"people":[]}}

Then, go to the following website:
http://jsonprettyprint.com/

And paste the response you grabbed above into the textbox provided and then click on "Pretty Pretty Json Print". This should make it easier to read then e.g.



{
  "added": {
    "movies": 10,
    "shows": 0,
    "seasons": 0,
    "episodes": 0
  },
  "not_found": {
    "movies": [
      {
        "ids": null,
        "title": "Breaking Bad",
        "year": 2008,
        "rated_at": "2015-10-17T04:33:00Z",
        "rating": 9
      },
      {
        "ids": null,
        "title": "South Park",
        "year": 1997,
        "rated_at": "2015-10-17T04:06:00Z",
        "rating": 9
      },
      {
        "ids": null,
        "title": "Naruto: Shipp\u00fbden",
        "year": 2007,
        "rated_at": "2016-08-06T04:58:00Z",
        "rating": 9
      },
      {
        "ids": null,
        "title": "Rocko's Modern Life",
        "year": 1993,
        "rated_at": "2015-10-17T02:02:00Z",
        "rating": 9
      },
      {
        "ids": null,
        "title": "South Park: Bigger, Longer, and Uncut",
        "year": 1999,
        "rated_at": "2013-03-21T00:10:00Z",
        "rating": 9
      },
      {
        "ids": null,
        "title": "Animaniacs",
        "year": 1993,
        "rated_at": "2015-10-17T02:22:00Z",
        "rating": 9
      },
      {
        "ids": null,
        "title": "Invader ZIM",
        "year": 2001,
        "rated_at": "2015-10-17T02:07:00Z",
        "rating": 9
      },
      {
        "ids": null,
        "title": "Band of Brothers",
        "year": 2001,
        "rated_at": "2013-03-21T02:10:00Z",
        "rating": 9
      },
      {
        "ids": null,
        "title": "Curb Your Enthusiasm",
        "year": 1999,
        "rated_at": "2015-10-17T04:22:00Z",
        "rating": 9
      },
      {
        "ids": null,
        "title": "Hey Arnold!",
        "year": 1996,
        "rated_at": "2015-10-17T02:03:00Z",
        "rating": 9
      },
      {
        "ids": null,
        "title": "It's Always Sunny in Philadelphia",
        "year": 2005,
        "rated_at": "2015-10-17T04:13:00Z",
        "rating": 9
      },
      {
        "ids": null,
        "title": "The Pacific",
        "year": 2010,
        "rated_at": "2013-03-21T02:09:00Z",
        "rating": 9
      },
      {
        "ids": null,
        "title": "Pinky and the Brain",
        "year": 1995,
        "rated_at": "2015-10-17T02:27:00Z",
        "rating": 9
      },
      {
        "ids": null,
        "title": "Samurai X: Trust and Betrayal",
        "year": 1999,
        "rated_at": "2013-03-21T17:36:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Superman: The Animated Series",
        "year": 1996,
        "rated_at": "2015-10-17T02:48:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Avatar: The Last Airbender",
        "year": 2005,
        "rated_at": "2015-10-17T02:09:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Tiny Toon Adventures",
        "year": 1990,
        "rated_at": "2015-10-17T02:27:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Cowboy Bebop",
        "year": 1998,
        "rated_at": "2016-08-06T20:52:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Kill Bill: Volume 1",
        "year": 2003,
        "rated_at": "2013-03-20T22:42:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Scrubs",
        "year": 2001,
        "rated_at": "2015-10-17T03:57:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "American Dad",
        "year": 2005,
        "rated_at": "2015-10-17T04:03:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Beast Wars: Transformers",
        "year": 1996,
        "rated_at": "2016-08-07T23:40:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Dragon Ball Z",
        "year": 1989,
        "rated_at": "2016-08-06T05:00:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Drawn Together",
        "year": 2004,
        "rated_at": "2015-10-17T04:10:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Harvey Birdman, Attorney at Law",
        "year": 2000,
        "rated_at": "2015-10-17T02:50:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Johnny Bravo",
        "year": 1997,
        "rated_at": "2015-10-17T02:40:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "The New Batman Adventures",
        "year": 1997,
        "rated_at": "2015-10-17T02:48:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Rugrats",
        "year": 1990,
        "rated_at": "2015-10-17T02:02:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Aaahh!!! Real Monsters",
        "year": 1994,
        "rated_at": "2015-10-17T02:03:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Kill Bill: Volume 2",
        "year": 2004,
        "rated_at": "2013-03-20T22:44:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Samurai X",
        "year": 1996,
        "rated_at": "2016-08-06T05:05:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Aqua Teen Hunger Force",
        "year": 2000,
        "rated_at": "2015-10-17T02:21:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Mobile Suit Gundam: The 08th MS Team",
        "year": 1996,
        "rated_at": "2016-08-06T05:13:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "The Ren & Stimpy Show",
        "year": 1991,
        "rated_at": "2015-10-17T02:02:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Russia, Land of the Tsars",
        "year": 2003,
        "rated_at": "2015-10-17T04:46:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "X2: X-Men United",
        "year": 2003,
        "rated_at": "2013-03-20T22:20:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Fullmetal Alchemist: Brotherhood",
        "year": 2009,
        "rated_at": "2016-08-06T05:21:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Batman: The Animated Series",
        "year": 1992,
        "rated_at": "2015-10-17T02:48:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Jackass",
        "year": 2000,
        "rated_at": "2015-10-17T22:15:00Z",
        "rating": 8
      },
      {
        "ids": null,
        "title": "Mobile Suit Gundam Wing",
        "year": 1995,
        "rated_at": "2016-08-06T05:12:00Z",
        "rating": 8
      }
    ],
    "shows": [
      
    ],
    "seasons": [
      
    ],
    "episodes": [
      
    ],
    "people": [
      
    ]
  }
}

You can now go through the list of movies it could not find.

**Comment by damienhaynes** [comment]
I can see some if not most of those a TV Shows and not Movies, thats why it failed to add them. I believe the export from Criticker does not indicate whether its a show or movie so I just assume its a movie.

**Comment by sneedsfeedandseed** [comment]
Ah I see. Alright, thanks man.

**Comment by damienhaynes** [comment]
It looks like Criticker has improved there export now. I can see a CSV export file which is easier to parse, it also indicates if it is a TV show in the Film URL. Also as an added bonus it contains the IMDb ID in the CSV so Im going to switch to using that now.

**Comment by damienhaynes** [comment]
Please try the new release (https://github.com/damienhaynes/TraktRater/releases/tag/2.3.2). Its much improved for Criticker. You will need to download the CSV file from your user profile.
